In [1]:
import numpy as np

In [102]:
class NeuralNetwork():
    def __init__(self, input_size=718, hidden_layers=[512, 512], output_size=10):
        self.input_size = input_size
        self.hidden_layers = hidden_layers
        self.output_size = output_size
        self.weights = []
        self.biases = []

        # Input to Hidden Layers Network
        self.weights.append(0.01 * np.random.rand(input_size, hidden_layers[0]))
        self.biases.append(np.zeros((1, hidden_layers[0])))

        # Hidden Layers Network
        for i in range(len(hidden_layers)-1):
            self.weights.append(0.01 * np.random.rand(hidden_layers[i], hidden_layers[i+1]))
            self.biases.append(np.zeros((1, hidden_layers[i+1])))
        
        # Hidden Layers Network to Output
        self.weights.append(0.01 * np.random.rand(hidden_layers[len(hidden_layers)-1], output_size))
        self.biases.append(np.zeros((1, output_size)))

    def forward(self, inputs):
        layers = [inputs]
        print(layers[-1].shape)

        for i in range(len(self.weights)):
            # Dot Product to 
            layers.append(np.dot(layers[-1], self.weights[i]) + self.biases[i])

            # Activation Functions (ReLU + SoftMax)
            if i == len(self.weights)-1:

                finalOutput = np.exp(layers[-1])
                sum = np.sum(finalOutput)
                finalOutput = finalOutput / sum
                layers.append(finalOutput)
            else:
                layers.append(np.maximum(0, layers[-1]))
            print(layers[-1].shape)
        
        return layers[-1]


In [103]:
myNeuralNet = NeuralNetwork()

In [105]:
result = myNeuralNet.forward(np.random.rand(1, 718))
result

(1, 718)
(1, 512)
(1, 512)
(1, 10)


array([[0.0864664 , 0.16715338, 0.10173483, 0.10064541, 0.09063523,
        0.07917663, 0.05446409, 0.13409147, 0.0851065 , 0.10052606]])

In [106]:
np.sum(result)

0.9999999999999999

In [93]:
test1 = np.array([1,2,3])
test1

array([1, 2, 3])

In [94]:
test1 += 30

In [95]:
test1 = np.exp(test1)
test1

array([2.90488497e+13, 7.89629602e+13, 2.14643580e+14])

In [96]:
sum = np.sum(test1)
sum

322655389633844.2

In [97]:
test1 = test1 / sum
test1

array([0.09003057, 0.24472847, 0.66524096])

In [83]:
np.sum(test1)

1.0

In [28]:
NeuralNetwork().weights

[array([[0.79876162, 0.90084167, 0.4401192 , ..., 0.98484349, 0.78392602,
         0.1411576 ],
        [0.14452771, 0.3616537 , 0.55987813, ..., 0.53699564, 0.80833471,
         0.90234479],
        [0.59664433, 0.83712402, 0.07534923, ..., 0.5817613 , 0.90192853,
         0.83691691],
        ...,
        [0.69490799, 0.31286115, 0.47560318, ..., 0.12409177, 0.67196322,
         0.69876002],
        [0.43198313, 0.30954852, 0.98144773, ..., 0.33922956, 0.78060173,
         0.44827809],
        [0.55082264, 0.63352575, 0.66652466, ..., 0.72324706, 0.94841395,
         0.6914613 ]]),
 array([[0.54007279, 0.14734038, 0.61046204, ..., 0.04570406, 0.04643376,
         0.63147651],
        [0.65448902, 0.84974573, 0.90313734, ..., 0.48914766, 0.46126397,
         0.50053977],
        [0.28161597, 0.77680599, 0.76626299, ..., 0.29413661, 0.61503144,
         0.62840997],
        ...,
        [0.28088512, 0.76910848, 0.20913243, ..., 0.98918204, 0.87833887,
         0.55507491],
        [0.8

In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

(batchNumber[32], inputs[718]) * (weights[718], weights[512]) = (32, 512)

- Implement GitHub Repo

Forward pass - Train 
    - Neurons + Acitvation function + Softwax (get probablities) + loss
    - Test Forward Pass with Other Model Gradients

Implement backpropagation
    - Explain how to do and everything
    - Start training with basic 80-20

Introduce regularization
Batch Normalization

Optimizer

Visualize gradients

Visualize MNIST with UMAP or T-SNE